server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VaccinationCenterDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: VACCINATION-CENTER-SERVICE

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,circuitbreaker
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      handleCitizenDownTime:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
     instances:
       citizenService:
           max-attempts: 3
           wait-duration: 5s
    
  ratelimiter:
    instances:
      citizenRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s         

